CREATE TABLE loan_application (
    Age INTEGER NOT NULL,
    AnnualIncome INTEGER NOT NULL,
    CreditScore INTEGER NOT NULL,
    EmploymentStatus TEXT NOT NULL,
    EducationLevel TEXT NOT NULL,
    Experience INTEGER NOT NULL,
    LoanAmount INTEGER NOT NULL,
    LoanDuration INTEGER NOT NULL,
    MaritalStatus TEXT NOT NULL,
    NumberOfDependents INTEGER NOT NULL,
    HomeOwnershipStatus TEXT NOT NULL,
    MonthlyDebtPayments INTEGER NOT NULL,
    LoanPurpose TEXT NOT NULL,
    SavingsAccountBalance INTEGER NOT NULL,
    CheckingAccountBalance INTEGER NOT NULL,
    MonthlyIncome INTEGER NOT NULL,
    JobTenure INTEGER NOT NULL,
    NetWorth INTEGER NOT NULL,
    BaseInterestRate DOUBLE PRECISION NOT NULL,
    InterestRate DOUBLE PRECISION NOT NULL,
    MonthlyLoanPayment INTEGER NOT NULL
);
